version: "3.7"

services:
  idp:
    image: eldari/ad4t.identityprovider:dev
    ports:
      - "44395:80"
    #restart: always
    depends_on:
      - postgres
      
  api:
    image: eldari/pw.api:dev
    ports:
      - "5135:80"
    #restart: always
    depends_on:
      - idp
  
  spa:
    image: eldari/parrotwings:dev
    ports:
      - "4200:80"
    depends_on:
      - api
      
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: idp
    volumes:
      - dbdata:/var/lib/postgresql/data
    command: -c log_statement=all

volumes:
  dbdata: